version: '3'
services:
  server:
    build:
      context: ../.
      dockerfile: docker/server/dev.dockerfile
    image: myapp-server
    deploy:
      resources:
        limits:
          cpus: '0.001'
          memory: 50M
        reservations:
          cpus: '0.0001'
          memory: 20M
    ports:
      - '80:80' # Connect localhost 80 port to container 80 port
    links: # Link services to access http://app inside the container
      - app:app
  app:
    build:
      context: ../.
      dockerfile: docker/client/dev.dockerfile
    image: react-docker
    environment:
      - NODE_ENV=development
    volumes: # For webpack dev server to use our local files
      - ./../client:/usr/src/app